---
apiVesrion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          # image: docker.io/datawire/quote:0.4.1
          image: nouman74/angular-01:0.0.2
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
      